imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true

  # Controller
  cdigruttola\Module\SimpleBanner\Controller\SimpleBannerController:
    public: true
    class: cdigruttola\Module\SimpleBanner\Controller\SimpleBannerController
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getLanguages(false)"

  # config form
  cdigruttola.module.simplebanner.configuration:
    class: 'cdigruttola\Module\SimpleBanner\Form\DataConfiguration\SimpleBannerDataConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'

  cdigruttola.module.simplebanner.configuration.form_provider:
    class: 'cdigruttola\Module\SimpleBanner\Form\Provider\SimpleBannerConfigurationFormDataProvider'
    arguments:
      - '@cdigruttola.module.simplebanner.configuration'

  cdigruttola.module.simplebanner.configuration.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@cdigruttola.module.simplebanner.configuration.form_provider'
      - 'cdigruttola\Module\SimpleBanner\Form\SimpleBannerConfigurationType'
      - 'BannerConfigurationForm'

  cdigruttola.module.simplebanner.form.banner_configuration_type:
    class: 'cdigruttola\Module\SimpleBanner\Form\SimpleBannerConfigurationType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
